### ISSUE TITLE
[16.0] l10n_do_accounting: Expected singleton on res.currency

### ISSUE THREAD

**Issue by crbll0** [indexa-git/l10n-dominicana#1130]
Type: General

Odoo Version: 16.0 EE
Factura de cliente de credito fiscal registrada en USD ya posteada, da el siguiente error cuando se intenta imprimir.

**Stack Trace**
```
RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/models.py", line 5165, in ensure_one
    _id, = self._ids
ValueError: too many values to unpack (expected 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<2251>", line 577, in template_2251
  File "<2251>", line 12, in template_2251_content
  File "/home/odoo/src/user/indexa-git/l10n-dominicana/l10n_do_accounting/models/account_move.py", line 213, in _get_l10n_do_amounts
    return self.line_ids._get_l10n_do_line_amounts()
  File "/home/odoo/src/user/indexa-git/l10n-dominicana/l10n_do_accounting/models/account_move_line.py", line 75, in _get_l10n_do_line_amounts
    "itbis_18_tax_amount": sum(
  File "/home/odoo/src/user/indexa-git/l10n-dominicana/l10n_do_accounting/models/account_move_line.py", line 76, in <genexpr>
    self.currency_id.round(line.amount_currency)
  File "/home/odoo/src/odoo/odoo/addons/base/models/res_currency.py", line 208, in round
    self.ensure_one()
  File "/home/odoo/src/odoo/odoo/models.py", line 5168, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: res.currency(2, 73)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/addons/web/controllers/report.py", line 113, in report_download
    response = self.report_routes(reportname, docids=docids, converter=converter, context=context)
  File "/home/odoo/src/odoo/odoo/http.py", line 697, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/home/odoo/src/user/OCA/reporting-engine/report_xlsx_helper/controllers/main.py", line 52, in report_routes
    return super().report_routes(reportname, docids, converter, **data)
  File "/home/odoo/src/odoo/odoo/http.py", line 697, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/home/odoo/src/user/OCA/reporting-engine/report_xlsx/controllers/main.py", line 49, in report_routes
    return super().report_routes(reportname, docids, converter, **data)
  File "/home/odoo/src/odoo/odoo/http.py", line 697, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/home/odoo/src/odoo/addons/web/controllers/report.py", line 42, in report_routes
    pdf = report.with_context(context)._render_qweb_pdf(reportname, docids, data=data)[0]
  File "/home/odoo/src/odoo/addons/account/models/ir_actions_report.py", line 58, in _render_qweb_pdf
    return super()._render_qweb_pdf(report_ref, res_ids=res_ids, data=data)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_actions_report.py", line 819, in _render_qweb_pdf
    collected_streams = self._render_qweb_pdf_prepare_streams(report_ref, data, res_ids=res_ids)
  File "/home/odoo/src/odoo/addons/account_edi_ubl_cii/models/ir_actions_report.py", line 58, in _render_qweb_pdf_prepare_streams
    collected_streams = super()._render_qweb_pdf_prepare_streams(report_ref, data, res_ids=res_ids)
  File "/home/odoo/src/odoo/addons/account_edi/models/ir_actions_report.py", line 14, in _render_qweb_pdf_prepare_streams
    collected_streams = super()._render_qweb_pdf_prepare_streams(report_ref, data, res_ids=res_ids)
  File "/home/odoo/src/odoo/addons/account/models/ir_actions_report.py", line 20, in _render_qweb_pdf_prepare_streams
    return super()._render_qweb_pdf_prepare_streams(report_ref, data, res_ids=res_ids)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_actions_report.py", line 708, in _render_qweb_pdf_prepare_streams
    html = self.with_context(**additional_context)._render_qweb_html(report_ref, res_ids_wo_stream, data=data)[0]
  File "/home/odoo/src/enterprise/web_studio/models/ir_actions_report.py", line 19, in _render_qweb_html
    return super(IrActionsReport, self)._render_qweb_html(report_ref, docids, data)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_actions_report.py", line 896, in _render_qweb_html
    return self._render_template(report.report_name, data), 'html'
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_actions_report.py", line 623, in _render_template
    return view_obj._render_template(template, values).encode()
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_ui_view.py", line 2125, in _render_template
    return self.env['ir.qweb']._render(template, values)
  File "/home/odoo/src/odoo/odoo/tools/profiler.py", line 292, in _tracked_method_render
    return method_render(self, template, values, **options)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_qweb.py", line 581, in _render
    result = ''.join(rendering)
  File "<694>", line 110, in template_694
  File "<694>", line 92, in template_694_content
  File "<694>", line 80, in template_694_t_call_0
  File "<2252>", line 1926, in template_2252
  File "<2252>", line 1908, in template_2252_content
  File "<2252>", line 1062, in template_2252_t_call_0
  File "<2251>", line 583, in template_2251
odoo.addons.base.models.ir_qweb.QWebException: Error while render the template
ValueError: Expected singleton: res.currency(2, 73)
Template: l10n_do_accounting.document_tax_totals
Path: /t/t[2]
Node: <t t-foreach="tax_totals[\'subtotals\']" t-as="subtotal"/>

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    RPCError@https://equiportsrl.odoo.com/web/assets/617-b7e33cb/web.assets_backend.min.js:993:274
    makeErrorFromResponse@https://equiportsrl.odoo.com/web/assets/617-b7e33cb/web.assets_backend.min.js:997:163
    configureBlobDownloadXHR/xhr.onload/decoder.onload@https://equiportsrl.odoo.com/web/assets/617-b7e33cb/web.assets_backend.min.js:984:7
```

**Comment by jlopezg** [comment]
Corregido en #1154
