### ISSUE TITLE
Odoo 14 _get_last_sequence tratando de crear factura de ventas.

### ISSUE THREAD

**Issue by ljacobo** [indexa-git/l10n-dominicana#1138]
Type: General

He configurado la parte de la localización en la version 14 de Odoo, pero al tratar de crear una factura de ventas, me da el error:

File "/mnt/extra-addons/l10n_do_accounting/models/account_move.py", line 905, in _get_last_sequence

Traté actualizando a la version que tiene el FIX, según leí en los issues reportados, pero tampoco funciona.

Tenemos alguna forma de resolver esto?

Gracias.

Exception

**Describe the bug**
Odoo Version: 
[A clear and concise description of the bug]

**Steps to Reproduce**

**Expected behavior**
[A clear and concise description of your expectation]

**Additional context and screenshots**
[Add any other information such as screenshots, videos, messages]

**Sample Code / Stack Trace**
```
XXX
```

**Configuration information**
Operating System:
Python version:

**Comment by jlopezg** [comment]
Hola @ljacobo 

Podrías complementar la descripción del issue con el Traceback **completo** del error?

**Comment by jlopezg** [comment]
Ping @ljacobo

**Comment by ljacobo** [comment]
Perdona, opté por la v12.

**Comment by ljacobo** [comment]
@jlopezg tratando nuevamente con Odoo v14 CE, acá el Traceback completo, por si puedes ayudarme:

Odoo Server Error
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 347, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 912, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1377, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1369, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/account/models/account_move.py", line 1048, in onchange
    return super(AccountMove, self.with_context(recursive_onchanges=False)).onchange(values, field_name, field_onchange)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 6228, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5984, in _onchange_eval
    method_res = method(self)
  File "/usr/lib/python3/dist-packages/odoo/addons/account/models/account_move.py", line 378, in _onchange_journal
    if self.state == 'draft' and self._get_last_sequence() and self.name and self.name != '/':
  File "/mnt/extra-addons/l10n_do_accounting/models/account_move.py", line 907, in _get_last_sequence
    relaxed=relaxed, lock=lock
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
TypeError: _get_last_sequence() got an unexpected keyword argument 'lock'

**Comment by ljacobo** [comment]
@jlopezg tratando nuevamente con Odoo v14 CE, acá el Traceback completo, por si puedes ayudarme:

Odoo Server Error
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
result = request.dispatch()
File "/usr/lib/python3/dist-packages/odoo/http.py", line 683, in dispatch
result = self._call_function(**self.params)
File "/usr/lib/python3/dist-packages/odoo/http.py", line 359, in _call_function
return checked_call(self.db, *args, **kwargs)
File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
return f(dbname, *args, **kwargs)
File "/usr/lib/python3/dist-packages/odoo/http.py", line 347, in checked_call
result = self.endpoint(*a, **kw)
File "/usr/lib/python3/dist-packages/odoo/http.py", line 912, in call
return self.method(*args, **kw)
File "/usr/lib/python3/dist-packages/odoo/http.py", line 531, in response_wrap
response = f(*args, **kw)
File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1377, in call_kw
return self._call_kw(model, method, args, kwargs)
File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1369, in _call_kw
return call_kw(request.env[model], method, args, kwargs)
File "/usr/lib/python3/dist-packages/odoo/api.py", line 396, in call_kw
result = _call_kw_multi(method, model, args, kwargs)
File "/usr/lib/python3/dist-packages/odoo/api.py", line 383, in _call_kw_multi
result = method(recs, *args, **kwargs)
File "/usr/lib/python3/dist-packages/odoo/addons/account/models/account_move.py", line 1048, in onchange
return super(AccountMove, self.with_context(recursive_onchanges=False)).onchange(values, field_name, field_onchange)
File "/usr/lib/python3/dist-packages/odoo/models.py", line 6228, in onchange
record._onchange_eval(name, field_onchange[name], result)
File "/usr/lib/python3/dist-packages/odoo/models.py", line 5984, in _onchange_eval
method_res = method(self)
File "/usr/lib/python3/dist-packages/odoo/addons/account/models/account_move.py", line 378, in _onchange_journal
if self.state == 'draft' and self._get_last_sequence() and self.name and self.name != '/':
File "/mnt/extra-addons/l10n_do_accounting/models/account_move.py", line 907, in _get_last_sequence
relaxed=relaxed, lock=lock
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/odoo/http.py", line 639, in _handle_exception
return super(JsonRequest, self)._handle_exception(exception)
File "/usr/lib/python3/dist-packages/odoo/http.py", line 315, in _handle_exception
raise exception.with_traceback(None) from new_cause
TypeError: _get_last_sequence() got an unexpected keyword argument 'lock'

**Comment by ljacobo** [comment]
También pasa al recibir productos en orden de compras:

Odoo Server Error
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 347, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 912, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1381, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1369, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/stock/wizard/stock_immediate_transfer.py", line 65, in process
    return pickings_to_validate.with_context(skip_immediate=True).button_validate()
  File "/usr/lib/python3/dist-packages/odoo/addons/stock/models/stock_picking.py", line 933, in button_validate
    pickings_to_backorder.with_context(cancel_backorder=False)._action_done()
  File "/usr/lib/python3/dist-packages/odoo/addons/sale_stock/models/stock.py", line 76, in _action_done
    res = super()._action_done()
  File "/usr/lib/python3/dist-packages/odoo/addons/stock/models/stock_picking.py", line 754, in _action_done
    todo_moves._action_done(cancel_backorder=self.env.context.get('cancel_backorder'))
  File "/usr/lib/python3/dist-packages/odoo/addons/stock_account/models/stock_move.py", line 268, in _action_done
    svl.stock_move_id._account_entry_move(svl.quantity, svl.description, svl.id, svl.value)
  File "/usr/lib/python3/dist-packages/odoo/addons/stock_account/models/stock_move.py", line 480, in _account_entry_move
    self.with_company(company_to)._create_account_move_line(acc_src, acc_valuation, journal_id, qty, description, svl_id, cost)
  File "/usr/lib/python3/dist-packages/odoo/addons/stock_account/models/stock_move.py", line 454, in _create_account_move_line
    'move_type': 'entry',
  File "<decorator-gen-206>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 344, in _model_create_multi
    return create(self, [arg])
  File "/usr/lib/python3/dist-packages/odoo/addons/purchase/models/account_invoice.py", line 102, in create
    moves = super(AccountMove, self).create(vals_list)
  File "<decorator-gen-170>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "/usr/lib/python3/dist-packages/odoo/addons/account/models/account_move.py", line 1820, in create
    rslt = super(AccountMove, self).create(vals_list)
  File "<decorator-gen-131>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_thread.py", line 264, in create
    threads = super(MailThread, self).create(vals_list)
  File "<decorator-gen-64>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_fields.py", line 533, in create
    recs = super().create(vals_list)
  File "<decorator-gen-13>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3866, in create
    records = self._create(data_list)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4026, in _create
    for other, data in zip(others, data_list)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 3035, in create
    self.write_batch(record_values, True)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 3061, in write_batch
    return self.write_real(records_commands_list, create)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 3233, in write_real
    flush()
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 3197, in flush
    comodel.create(to_create)
  File "<decorator-gen-171>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "/usr/lib/python3/dist-packages/odoo/addons/account/models/account_move.py", line 3747, in create
    vals.setdefault('company_currency_id', move.company_id.currency_id.id) # important to bypass the ORM limitation where monetary fields are not rounded; more info in the commit message
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 2483, in __get__
    return super().__get__(records, owner)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 967, in __get__
    self.recompute(record)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1153, in recompute
    self.compute_value(recs)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1175, in compute_value
    records._compute_field_value(self)
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_thread.py", line 410, in _compute_field_value
    return super()._compute_field_value(field)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4066, in _compute_field_value
    self.filtered('id')._validate_fields(fnames)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 1256, in _validate_fields
    check(self)
  File "/usr/lib/python3/dist-packages/odoo/addons/l10n_latam_invoice_document/models/account_move.py", line 260, in _check_unique_vendor_number
    lambda x: x.name and x.name != '/' and x.is_purchase_document() and x.l10n_latam_use_documents):
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5279, in filtered
    return self.browse([rec.id for rec in self if func(rec)])
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5279, in <listcomp>
    return self.browse([rec.id for rec in self if func(rec)])
  File "/usr/lib/python3/dist-packages/odoo/addons/l10n_latam_invoice_document/models/account_move.py", line 260, in <lambda>
    lambda x: x.name and x.name != '/' and x.is_purchase_document() and x.l10n_latam_use_documents):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 967, in __get__
    self.recompute(record)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1153, in recompute
    self.compute_value(recs)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1175, in compute_value
    records._compute_field_value(self)
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_thread.py", line 410, in _compute_field_value
    return super()._compute_field_value(field)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4059, in _compute_field_value
    getattr(self, field.compute)()
  File "/mnt/extra-addons/l10n_do_accounting/models/monkey_patch.py", line 28, in _compute_name
    highest_name = self[0]._get_last_sequence(lock=False) if self else False
  File "/mnt/extra-addons/l10n_do_accounting/models/account_move.py", line 907, in _get_last_sequence
    relaxed=relaxed, lock=lock
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
TypeError: _get_last_sequence() got an unexpected keyword argument 'lock'

**Comment by jlopezg** [comment]
Hola @ljacobo 
Este error debe resolverse usando una versión actualizada de Odoo 14.

¿Puedes compartir por acá cuál es el último commit que tienes de Odoo en esa versión?

**Comment by ljacobo** [comment]
@jlopezg gracias. Tenía una imagen de Odoo 14 un poco out of date, actualicé la imagen y listo.

Por otro lado, puedo contactarte por otro canal persona, email o ws, para consultarte algo sobre tus servicios profesionales de Odoo?

Mil gracias.

**Comment by jlopezg** [comment]
Hola @ljacobo 

Por supuesto. Mi correo es jlopez@indexa.do
