### ISSUE TITLE
Problema al instalar el modulo

### ISSUE THREAD

**Issue by ctactuk** [indexa-git/l10n-dominicana#1168]
Type: General
Problema al instalar el modulo

**Describe the bug**
Odoo Version 17: 
RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1768, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1795, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1999, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 222, in _dispatch
    result = endpoint(**request.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 725, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/dataset.py", line 28, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/dataset.py", line 20, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 468, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 453, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-77>", line 2, in button_immediate_install
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 75, in check_and_log
    return method(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 466, in button_immediate_install
    return self._button_immediate_function(self.env.registry[self._name].button_install)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 590, in _button_immediate_function
    registry = modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "<decorator-gen-16>", line 2, in new
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 113, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 480, in load_modules
    processed_modules += load_marked_modules(env, graph,
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 364, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 227, in load_module_graph
    load_data(env, idref, mode, kind='data', package=package)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 71, in load_data
    tools.convert_file(env, package.name, filename, idref, mode, noupdate, kind)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 627, in convert_file
    convert_xml_import(env, module, fp, idref, mode, noupdate)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 693, in convert_xml_import
    obj.parse(doc.getroot())
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 613, in parse
    self._tag_root(de)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 567, in _tag_root
    raise ParseError(msg) from None  # Restart with "--log-handler odoo.tools.convert:DEBUG" for complete traceback
odoo.tools.convert.ParseError: while parsing /mnt/extra-addons/l10n_do_accounting/wizard/account_move_reversal_views.xml:4
Ocurrió un error al procesar o validar la vista:

El elemento "<xpath expr="//field[@name=&#39;refund_method&#39;]">" no se puede localizar en la vista principal

View error context:
{'file': '/mnt/extra-addons/l10n_do_accounting/wizard/account_move_reversal_views.xml',
 'line': 2,
 'name': 'view.account.move.reversal.inherited',
 'view': ir.ui.view(1279,),
 'view.model': 'account.move.reversal',
 'view.parent': ir.ui.view(625,),
 'xmlid': 'view_account_move_reversal_inherited'}

The above server error caused the following client error:
RPC_ERROR://localhost:8069/web/assets/4c7c187/web.assets_web.min.js:2870:163)
    at XMLHttpRequest.<anonymous> (http://localhost:8069/web/assets/4c7c187/web.assets_web.min.js:2874:13)

**Steps to Reproduce**
1. Go to 'Applications'
2. Click on 'Activar'

**Configuration information**
Operating System: Docker
Python version: 3.10.12

**Comment by dixgrake** [comment]
Hola @ctactuk 

Esta versión aún se encuentra en proceso de migración, por lo que no podrá utilizarla hasta que se complete.

**Comment by jlopezg** [comment]
Hola @ctactuk 
Ya hicimos merge a la rama 17.0
Puedes probar todo otra vez.

**Comment by ctactuk** [comment]
@jlopezg Gracias, voy a probar. Me gustaría colaborar en este repo.

**Comment by jlopezg** [comment]
Hola @ctactuk 
¿Algún feedback sobre tus pruebas?

**Comment by ctactuk** [comment]
Por el momento está todo bien. estoy verificando todo. cualquier observación te dejo saber.

> Hola @ctactuk ¿Algún feedback sobre tus pruebas?
