### ISSUE TITLE
[17.0][BUG] l10n_do_accounting: _name_search() Order parameter is missing.

### ISSUE THREAD

**Issue by crbll0** [indexa-git/l10n-dominicana#1182]
Type: General

Describe the bug

Tener un campo relacionado al modelo *account.move* y tratar de seleccionar alguna factura/asiento.

RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/http.py", line 1764, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/home/odoo/src/odoo/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/home/odoo/src/odoo/odoo/http.py", line 1791, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/home/odoo/src/odoo/odoo/http.py", line 1995, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/home/odoo/src/odoo/addons/website/models/ir_http.py", line 235, in _dispatch
    response = super()._dispatch(endpoint)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_http.py", line 222, in _dispatch
    result = endpoint(**request.params)
  File "/home/odoo/src/odoo/odoo/http.py", line 741, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/home/odoo/src/odoo/addons/web/controllers/dataset.py", line 24, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/src/odoo/addons/web/controllers/dataset.py", line 20, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 464, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 435, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/models.py", line 1735, in name_search
    ids = self._name_search(name, args, operator, limit=limit, order=self._order)
TypeError: AccountMove._name_search() got an unexpected keyword argument 'order'

Hey @jlopezg El metodo _name_search() se esta sobreescribiendo y le esta faltando el parametro orden.
  https://github.com/indexa-git/l10n-dominicana/blob/66560cd983fdf048ce5a7dfb7ed5eb1b8d75c49e/l10n_do_accounting/models/account_move.py#L194

**Comment by crbll0** [comment]
Esto fue corregido en el commit #1183 .
