### ISSUE TITLE
dgii_reports No such file or directory: '/tmp/DGII_606_131775578_202002.txt' en Windows

### ISSUE THREAD

**Issue by JpGarciiia964** [indexa-git/l10n-dominicana#773]
Type: General

**Describe the bug**
Odoo Version: 12
Al momento de generar los reportes fiscales del modulo "dgii_reports" se me generar el siguiente error:

Error:
Odoo Server Error

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\tools\pycompat.py", line 87, in reraise
    raise value
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\service\model.py", line 98, in wrapper
    return f(dbname, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "c:\program files (x86)\odoo 12.0\server\odoo\addons\web\controllers\main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "c:\program files (x86)\odoo 12.0\server\odoo\addons\web\controllers\main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "c:\program files (x86)\odoo 12.0\server\odoo\addons\dgii_reports\models\dgii_report.py", line 1083, in generate_report
    self._generate_report()
  File "c:\program files (x86)\odoo 12.0\server\odoo\addons\dgii_reports\models\dgii_report.py", line 1069, in _generate_report
    self._compute_606_data()
  File "c:\program files (x86)\odoo 12.0\server\odoo\addons\dgii_reports\models\dgii_report.py", line 536, in _compute_606_data
    self._generate_606_txt(report_data, line)
  File "c:\program files (x86)\odoo 12.0\server\odoo\addons\dgii_reports\models\dgii_report.py", line 450, in _generate_606_txt
    with open(file_path, 'w', encoding="utf-8", newline='\r\n') as txt_606:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/DGII_606_131775578_202002.txt'

**Steps to Reproduce**
1. Go to 'Menu DGII ---> Informes'
2. Click on 'Botón Crear ---> Digitar el periodo de los reportes "MM/AAAA" ---> Click en el boton Generar Reportes'

Error:
Odoo Server Error

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\tools\pycompat.py", line 87, in reraise
    raise value
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\service\model.py", line 98, in wrapper
    return f(dbname, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "c:\program files (x86)\odoo 12.0\server\odoo\addons\web\controllers\main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "c:\program files (x86)\odoo 12.0\server\odoo\addons\web\controllers\main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "c:\program files (x86)\odoo 12.0\server\odoo\addons\dgii_reports\models\dgii_report.py", line 1083, in generate_report
    self._generate_report()
  File "c:\program files (x86)\odoo 12.0\server\odoo\addons\dgii_reports\models\dgii_report.py", line 1069, in _generate_report
    self._compute_606_data()
  File "c:\program files (x86)\odoo 12.0\server\odoo\addons\dgii_reports\models\dgii_report.py", line 536, in _compute_606_data
    self._generate_606_txt(report_data, line)
  File "c:\program files (x86)\odoo 12.0\server\odoo\addons\dgii_reports\models\dgii_report.py", line 450, in _generate_606_txt
    with open(file_path, 'w', encoding="utf-8", newline='\r\n') as txt_606:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/DGII_606_131775578_202102.txt'
**Expected behavior**
Generar reportes fiscales.

**Configuration information**
Operating System: Windows
Python version: 3

**Comment by andrp92** [comment]
Hola @JpGarciiia964 ,

Esto es un issue del SO y no del módulo. Windows no posee carpeta temp como los sistemas Unix based. Un workaround que pudieras probar es crear una carpeta tmp en el root.

**Comment by JpGarciiia964** [comment]
> Hola @JpGarciiia964 ,
> 
> Esto es un issue del SO y no del módulo. Windows no posee carpeta temp como los sistemas Unix based. Un workaround que pudieras probar es crear una carpeta tmp en el root.

Gracias Andres, no lo había de ese modo.
