### ISSUE TITLE
[13.0] l10n_do_accounting: psycopg2.ProgrammingError al actualizar módulo

### ISSUE THREAD

**Issue by crbll0** [indexa-git/l10n-dominicana#777]
Type: General/

**Describe the bug**
Odoo Version: v13.0
Cuando se le hace un pull para actualizar la branch 13.0 estando desde el commit (0e021b5)  esto trae campos nuevos y la instancia no termina de subir por que no encuentras los campos (l10n_do_ecf_issuer y l10n_do_itbis_amount), se intenta actualiza el módulo por terminal pero  no termina de actualizar el modulo.

Track del ISSUE:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/home/odoo/src/odoo/odoo/service/server.py", line 439, in app
    return self.app(e, s)
  File "/home/odoo/src/odoo/odoo/service/wsgi_server.py", line 140, in application
    return ProxyFix(application_unproxied)(environ, start_response)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/contrib/fixers.py", line 152, in __call__
    return self.app(environ, start_response)
  File "/home/odoo/src/odoo/odoo/service/wsgi_server.py", line 117, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/home/odoo/src/odoo/odoo/http.py", line 1287, in __call__
    return self.dispatch(environ, start_response)
  File "/home/odoo/src/odoo/odoo/http.py", line 1257, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/wsgi.py", line 766, in __call__
    return self.app(environ, start_response)
  File "/home/odoo/src/odoo/odoo/http.py", line 1457, in dispatch
    result = ir_http._dispatch()
  File "/home/odoo/src/odoo/addons/website_sale/models/ir_http.py", line 15, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/home/odoo/src/odoo/addons/website/models/ir_http.py", line 172, in _dispatch
    response = super(Http, cls)._dispatch()
  File "/home/odoo/src/odoo/addons/auth_signup/models/ir_http.py", line 19, in _dispatch
    return super(Http, cls)._dispatch()
  File "/home/odoo/src/odoo/addons/web_editor/models/ir_http.py", line 21, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/home/odoo/src/odoo/addons/utm/models/ir_http.py", line 29, in _dispatch
    response = super(IrHttp, cls)._dispatch()
  File "/home/odoo/src/odoo/addons/http_routing/models/ir_http.py", line 519, in _dispatch
    result = super(IrHttp, cls)._dispatch()
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_http.py", line 238, in _dispatch
    return cls._handle_exception(e)
  File "/home/odoo/src/odoo/addons/utm/models/ir_http.py", line 34, in _handle_exception
    response = super(IrHttp, cls)._handle_exception(exc)
  File "/home/odoo/src/odoo/addons/http_routing/models/ir_http.py", line 610, in _handle_exception
    return super(IrHttp, cls)._handle_exception(exception)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_http.py", line 206, in _handle_exception
    return request._handle_exception(exception)
  File "/home/odoo/src/odoo/odoo/http.py", line 750, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/odoo/src/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_http.py", line 234, in _dispatch
    result = request.dispatch()
  File "/home/odoo/src/odoo/odoo/http.py", line 809, in dispatch
    r = self._call_function(**self.params)
  File "/home/odoo/src/odoo/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/odoo/addons/portal/controllers/web.py", line 26, in web_client
    return super(Home, self).web_client(s_action, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 849, in web_client
    context = request.env['ir.http'].webclient_rendering_context()
  File "/home/odoo/src/enterprise/web_enterprise/models/ir_http.py", line 16, in webclient_rendering_context
    'session_info': self.session_info(),
  File "/home/odoo/src/odoo/addons/hr_timesheet/models/ir_http.py", line 14, in session_info
    result = super(Http, self).session_info()
  File "/home/odoo/src/enterprise/web_studio/controllers/ir_http.py", line 12, in session_info
    result = super(IrHttp, self).session_info()
  File "/home/odoo/src/odoo/addons/mail_bot/models/ir_http.py", line 11, in session_info
    res = super(Http, self).session_info()
  File "/home/odoo/src/enterprise/web_map/models/ir_http.py", line 11, in session_info
    result = super(IrHttp, self).session_info()
  File "/home/odoo/src/odoo/addons/mail/models/ir_http.py", line 13, in session_info
    result = super(IrHttp, self).session_info()
  File "/home/odoo/src/odoo/addons/web_tour/models/ir_http.py", line 12, in session_info
    result = super(Http, self).session_info()
  File "/home/odoo/src/enterprise/web_enterprise/models/ir_http.py", line 30, in session_info
    result = super(Http, self).session_info()
  File "/home/odoo/src/enterprise/web_dashboard/models/ir_http.py", line 11, in session_info
    res = super(IrHttp, self).session_info()
  File "/home/odoo/src/odoo/addons/base_setup/models/ir_http.py", line 11, in session_info
    result = super(IrHttp, self).session_info()
  File "/home/odoo/src/odoo/addons/barcodes/models/ir_http.py", line 11, in session_info
    res = super(IrHttp, self).session_info()
  File "/home/odoo/src/odoo/addons/web/models/ir_http.py", line 62, in session_info
    "user_companies": {'current_company': (user.company_id.id, user.company_id.name), 'allowed_companies': [(comp.id, comp.name) for comp in user.company_ids]},
  File "/home/odoo/src/odoo/odoo/fields.py", line 1044, in __get__
    recs._fetch_field(self)
  File "/home/odoo/src/odoo/odoo/models.py", line 2994, in _fetch_field
    self._read(fnames)
  File "/home/odoo/src/odoo/odoo/models.py", line 3066, in _read
    cr.execute(query_str, params)
  File "/home/odoo/src/odoo/odoo/sql_db.py", line 173, in wrapper
    return f(self, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/sql_db.py", line 250, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: column res_company.l10n_do_ecf_issuer does not exist
LINE 1: ...0n_do_default_client" as "l10n_do_default_client","res_compa...
                                                             ^ - - -

**Expected behavior**
Actualizacion sin inconvenientes.

Posible solucion que probé y funciono. (hay que analizar más)
En el archivo l10n_do_accounting/models/__init__.py mover la ultima linea  "from . import account_move_line" al principio del archivo.

**Comment by juhenriquez** [comment]
Confirmo este issue, cuando actualizo desde commit cc1ecf9232fb9354c71ed4de99a10cd7a1bc514e hacia el commit fa3f28961d69057a2239f8770352cdac4e681701

**Comment by akevinieron** [comment]
Incidencia circunstancial. Difícilmente repetible a estas alturas. Versión sin soporte.
