### ISSUE TITLE
Error al crear Nota de Debito.

### ISSUE THREAD

**Issue by crbll0** [indexa-git/l10n-dominicana#803]
Type: General
@jlopezg 
**Describe the bug**
Odoo Version: 
* v13 E.E
* Localizacion actualizada al commit: #8e55f06

**Steps to Reproduce**
1. Ir a una factura de cliente o proveedor
2. clickear el boton "APLICAR NOTA DE DEBITO"
3. Asignamos monto de la nota de debito.
4. clickeamos boton "Crear Nota de Debito"

Al relizar estos pasos nos lanza el siguiente error.

**Stack Trace**
```
Odoo Server Error

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/odoo/src/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/home/odoo/src/odoo/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/src/odoo/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1343, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1331, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 387, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 374, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/src/user/l10n-dominicana/l10n_do_debit_note/wizard/account_debit_note.py", line 149, in create_debit
    reason=self.reason,
  File "/home/odoo/src/odoo/addons/account_debit_note/wizard/account_debit_note.py", line 68, in create_debit
    new_move = move.with_context(internal_type='debit_note').copy(default=default_values) # Context key is used for l10n_latam_invoice_document for ar/cl/pe
  File "/home/odoo/src/odoo/addons/account/models/account_move.py", line 1781, in copy
    rec = super().copy(default)
  File "/home/odoo/src/odoo/odoo/models.py", line 4664, in copy
    new = self.with_context(lang=None).create(vals)
  File "<decorator-gen-212>", line 2, in create
  File "/home/odoo/src/odoo/odoo/api.py", line 335, in _model_create_multi
    return create(self, [arg])
  File "/home/odoo/src/odoo/addons/purchase/models/account_invoice.py", line 104, in create
    moves = super(AccountMove, self).create(vals_list)
  File "<decorator-gen-201>", line 2, in create
  File "/home/odoo/src/odoo/odoo/api.py", line 317, in _model_create_single
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/home/odoo/src/odoo/odoo/models.py", line 5627, in concat
    raise TypeError("Mixing apples and oranges: %s.concat(%s)" % (self, arg))
TypeError: Mixing apples and oranges: account.move().concat(None)
```

**Comment by jlopezg** [comment]
Hola @crbll0 
Acabo de generar [esta](https://l10n-dominicana-13-0-fix-803-jl.indexa.do/web/login) instancia de prueba con el último commit del branch 13.0

¿Podrías intentar reproducir el issue en esa instancia?

**Comment by crbll0** [comment]
> Hola @crbll0
> Acabo de generar [esta](https://l10n-dominicana-13-0-fix-803-jl.indexa.do/web/login) instancia de prueba con el último commit del branch 13.0
> 
> ¿Podrías intentar reproducir el issue en esa instancia?

Acabo de hacer la prueba en la instancia que suministra, pero no puedo reproducir el bug. revisare que otra cosa puede estar pasando para documentar mejor el bug.

**Comment by jlopezg** [comment]
@crbll0 algún update de tus pruebas?

**Comment by jlopezg** [comment]
Cerrado por falta de seguimiento.
