### ISSUE TITLE
Error al Instalar: l10n_do_debit_note

### ISSUE THREAD

**Issue by crbll0** [indexa-git/l10n-dominicana#903]
Type: General
Odoo Version: 13.0
Odoo Server Error
Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_ui_view.py", line 671, in apply_inheritance_specs
    pre_locate=pre_locate)
  File "/home/odoo/src/odoo/odoo/tools/template_inheritance.py", line 230, in apply_inheritance_specs
    _("Element '%s' cannot be located in parent view") % tag
ValueError: El elemento '<xpath expr="//form/sheet/div[2]/h1[1]">' no puede ser localizado en la vista padre

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/tools/convert.py", line 712, in parse
    self._tag_root(de)
  File "/home/odoo/src/odoo/odoo/tools/convert.py", line 674, in _tag_root
    f(rec)
  File "/home/odoo/src/odoo/odoo/tools/convert.py", line 577, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "/home/odoo/src/odoo/odoo/models.py", line 4183, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/home/odoo/src/odoo/odoo/models.py", line 4097, in _load_records_create
    return self.create(values)
  File "<decorator-gen-149>", line 2, in create
  File "/home/odoo/src/odoo/odoo/api.py", line 320, in _model_create_single
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/home/odoo/src/odoo/odoo/api.py", line 320, in <genexpr>
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/home/odoo/src/enterprise/web_studio/models/studio_mixin.py", line 19, in create
    res = super(StudioMixin, self).create(vals)
  File "<decorator-gen-32>", line 2, in create
  File "/home/odoo/src/odoo/odoo/api.py", line 338, in _model_create_multi
    return create(self, [arg])
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_ui_view.py", line 475, in create
    return super(View, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/home/odoo/src/odoo/odoo/api.py", line 339, in _model_create_multi
    return create(self, arg)
  File "/home/odoo/src/odoo/odoo/models.py", line 3858, in create
    fields[0].determine_inverse(batch_recs)
  File "/home/odoo/src/odoo/odoo/fields.py", line 1156, in determine_inverse
    getattr(records, self.inverse)()
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_ui_view.py", line 299, in _inverse_arch
    view.write(data)
  File "/home/odoo/src/enterprise/web_studio/models/studio_mixin.py", line 28, in write
    res = super(StudioMixin, self).write(vals)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_ui_view.py", line 493, in write
    res = super(View, self).write(self._compute_defaults(vals))
  File "/home/odoo/src/odoo/odoo/models.py", line 3647, in write
    real_recs._validate_fields(vals, inverse_fields)
  File "/home/odoo/src/odoo/odoo/models.py", line 1212, in _validate_fields
    check(self)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_ui_view.py", line 387, in _check_xml
    view_def = view.read_combined(['arch'])
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_ui_view.py", line 745, in read_combined
    arch = self.apply_view_inheritance(arch_tree, root.id, self.model)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_ui_view.py", line 694, in apply_view_inheritance
    source = self.apply_inheritance_specs(source, specs_tree, view_id)
  File "/home/odoo/src/enterprise/web_studio/models/ir_ui_view.py", line 154, in apply_inheritance_specs
    pre_locate=pre_locate)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_ui_view.py", line 673, in apply_inheritance_specs
    self.raise_view_error(str(e), inherit_id)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_ui_view.py", line 614, in raise_view_error
    raise ValueError(message)
ValueError: El elemento '<xpath expr="//form/sheet/div[2]/h1[1]">' no puede ser localizado en la vista padre

Contexto del error:
Vista `account.move.form.inherited`
[view_id: 4118, xml_id: n/a, model: account.move, parent_id: 867]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/odoo/src/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/home/odoo/src/odoo/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/src/odoo/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1343, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1331, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 390, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 377, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-60>", line 2, in button_immediate_install
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_module.py", line 73, in check_and_log
    return method(self, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_module.py", line 464, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_module.py", line 574, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/home/odoo/src/odoo/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 428, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 315, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 225, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/home/odoo/src/odoo/odoo/tools/convert.py", line 736, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/home/odoo/src/odoo/odoo/tools/convert.py", line 803, in convert_xml_import
    obj.parse(doc.getroot())
  File "/home/odoo/src/odoo/odoo/tools/convert.py", line 721, in parse
    exc_info[2]
  File "/home/odoo/src/odoo/odoo/tools/pycompat.py", line 13, in reraise
    raise value.with_traceback(tb)
  File "/home/odoo/src/odoo/odoo/tools/convert.py", line 712, in parse
    self._tag_root(de)
  File "/home/odoo/src/odoo/odoo/tools/convert.py", line 674, in _tag_root
    f(rec)
  File "/home/odoo/src/odoo/odoo/tools/convert.py", line 577, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "/home/odoo/src/odoo/odoo/models.py", line 4183, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/home/odoo/src/odoo/odoo/models.py", line 4097, in _load_records_create
    return self.create(values)
  File "<decorator-gen-149>", line 2, in create
  File "/home/odoo/src/odoo/odoo/api.py", line 320, in _model_create_single
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/home/odoo/src/odoo/odoo/api.py", line 320, in <genexpr>
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/home/odoo/src/enterprise/web_studio/models/studio_mixin.py", line 19, in create
    res = super(StudioMixin, self).create(vals)
  File "<decorator-gen-32>", line 2, in create
  File "/home/odoo/src/odoo/odoo/api.py", line 338, in _model_create_multi
    return create(self, [arg])
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_ui_view.py", line 475, in create
    return super(View, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/home/odoo/src/odoo/odoo/api.py", line 339, in _model_create_multi
    return create(self, arg)
  File "/home/odoo/src/odoo/odoo/models.py", line 3858, in create
    fields[0].determine_inverse(batch_recs)
  File "/home/odoo/src/odoo/odoo/fields.py", line 1156, in determine_inverse
    getattr(records, self.inverse)()
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_ui_view.py", line 299, in _inverse_arch
    view.write(data)
  File "/home/odoo/src/enterprise/web_studio/models/studio_mixin.py", line 28, in write
    res = super(StudioMixin, self).write(vals)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_ui_view.py", line 493, in write
    res = super(View, self).write(self._compute_defaults(vals))
  File "/home/odoo/src/odoo/odoo/models.py", line 3647, in write
    real_recs._validate_fields(vals, inverse_fields)
  File "/home/odoo/src/odoo/odoo/models.py", line 1212, in _validate_fields
    check(self)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_ui_view.py", line 387, in _check_xml
    view_def = view.read_combined(['arch'])
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_ui_view.py", line 745, in read_combined
    arch = self.apply_view_inheritance(arch_tree, root.id, self.model)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_ui_view.py", line 694, in apply_view_inheritance
    source = self.apply_inheritance_specs(source, specs_tree, view_id)
  File "/home/odoo/src/enterprise/web_studio/models/ir_ui_view.py", line 154, in apply_inheritance_specs
    pre_locate=pre_locate)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_ui_view.py", line 673, in apply_inheritance_specs
    self.raise_view_error(str(e), inherit_id)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_ui_view.py", line 614, in raise_view_error
    raise ValueError(message)
odoo.tools.convert.ParseError: "El elemento '<xpath expr="//form/sheet/div[2]/h1[1]">' no puede ser localizado en la vista padre

Contexto del error:
Vista `account.move.form.inherited`
[view_id: 4118, xml_id: n/a, model: account.move, parent_id: 867]" while parsing /home/odoo/src/user/indexa-git/l10n-dominicana/l10n_do_debit_note/views/account_views.xml:2, near
<odoo>

    <record id="view_move_form_inherited" model="ir.ui.view">
        <field name="name">account.move.form.inherited</field>
        <field name="model">account.move</field>
        <field name="inherit_id" ref="account.view_move_form"/>
        <field name="arch" type="xml">
            <data><field name="restrict_mode_hash_table" position="after">
                <field name="is_debit_note" invisible="1"/>
            </field>
            <xpath expr="//form/sheet/div[2]/h1[1]" position="inside">
                <span attrs="{'invisible': ['|', '|', ('type', 'not in', ('out_invoice', 'in_invoice')), ('state', '!=', 'cancel'), ('is_debit_note', '=', False)]}">Cancelled Debit Note</span>
            </xpath>
            <xpath expr="//form/sheet/div[2]/h1[1]" position="inside">
                <span attrs="{'invisible': ['|', '|', ('type', '!=', 'out_invoice'), ('state', '!=', 'cancel'), ('is_debit_note', '=', True)]}">Cancelled Invoice</span>
            </xpath>
            <xpath expr="//form/sheet/div[2]/h1[1]" position="inside">
                <span attrs="{'invisible': ['|', '|', ('type', '!=', 'in_invoice'), ('state', '!=', 'cancel'), ('is_debit_note', '=', True)]}">Cancelled Bill</span>
            </xpath>
            <xpath expr="//field[@name='l10n_do_origin_ncf']" position="attributes">
                <attribute name="attrs">{
                       'invisible':['|', '&amp;', ('type', 'not in', ('in_refund', 'out_refund')), ('is_debit_note', '=', False), '&amp;', ('type', 'in', ('in_refund', 'out_refund')), ('l10n_latam_use_documents', '=', False)],
                       'required': ['|', '&amp;', ('type', 'in', ('in_refund', 'out_refund')), ('l10n_latam_use_documents', '=', True), ('is_debit_note', '=', True)],
                       'readonly': [('state','!=','draft')
                ]}</attribute>
            </xpath>
            <xpath expr="//span/field[@name='type']" position="attributes">
                <attribute name="attrs">{'invisible': ['|', '|',
                    ('type', '=', 'entry'), ('state', '=', 'draft'), ('is_debit_note', '=', True)
                ]}</attribute>
            </xpath>
            <xpath expr="//span/field[@name='type']" position="attributes">
                <attribute name="attrs">{'invisible': ['|', '|',
                    ('type', '=', 'entry'),
                    ('state', 'in', ('draft', 'cancel')),
                    ('is_debit_note', '=', True),
                  ]}</attribute>
            </xpath>
            <xpath expr="//span/field[@name='type']" position="after">
                <span attrs="{'invisible': ['|', '|', ('type', '!=', 'out_invoice'), ('state', 'in', ('draft', 'cancel')), ('is_debit_note', '=', False)]}">Customer Debit Note</span>
            </xpath>
            <xpath expr="//form/sheet/div[2]/span[1]/field[@name='type']" position="after">
                <span attrs="{'invisible': ['|', '|', ('type', '!=', 'in_invoice'), ('state', 'in', ('draft', 'cancel')), ('is_debit_note', '=', False)]}">Vendor Debit Note</span>
            </xpath>
            <xpath expr="//h1/span[1]" position="attributes">
                <attribute name="attrs">{'invisible': ['|', '|', '|',
                    ('type', '!=', 'out_invoice'),
                    ('state', '!=', 'draft'),
                    ('name', '!=', '/'),
                    ('is_debit_note', '=', True)
                ]}</attribute>
            </xpath>
            <xpath expr="//h1/span[3]" position="attributes">
                <attribute name="attrs">{'invisible': ['|', '|', '|',
                    ('type', '!=', 'in_invoice'),
                    ('state', '!=', 'draft'),
                    ('name', '!=', '/'),
                    ('is_debit_note', '=', True)
                ]}</attribute>
            </xpath>
            <xpath expr="//h1/span/.." position="inside">
                <span attrs="{'invisible': ['|', '|', '|', ('type', '!=', 'out_invoice'), ('state', '!=', 'draft'), ('name', '!=', '/'), ('is_debit_note', '=', False)]}">Draft Debit Note</span>
            </xpath>
            <xpath expr="//h1/span/.." position="inside">
                <span attrs="{'invisible': ['|', '|', '|', ('type', '!=', 'in_invoice'), ('state', '!=', 'draft'), ('name', '!=', '/'), ('is_debit_note', '=', False)]}">Draft Vendor Debit Note</span>
            </xpath>
        </data></field>
    </record>

    
    <record id="account.action_move_out_invoice_type" model="ir.actions.act_window">
        <field name="domain">[('type', '=', 'out_invoice'), ('is_debit_note', '=', False)]</field>
    </record>
    <record id="account.action_move_in_invoice_type" model="ir.actions.act_window">
        <field name="domain">[('type', '=', 'in_invoice'), ('is_debit_note', '=', False)]</field>
    </record>

    
    <record id="action_invoice_out_debit_note" model="ir.actions.act_window">
        <field name="name">Debit Notes</field>
        <field name="res_model">account.move</field>
        <field name="view_mode">tree,kanban,form</field>
        <field name="view_ids" eval="[(5, 0, 0),                           (0, 0, {'view_mode': 'tree', 'view_id': ref('account.view_invoice_tree')}),                           (0, 0, {'view_mode': 'form', 'view_id': ref('account.view_move_form')})]"/>
        <field name="domain">[('type','=','out_invoice'), ('is_debit_note', '=', True)]</field>
        <field name="context">{
            'default_type': 'out_invoice',
            'type': 'out_invoice',
            'journal_type': 'sale',
            'default_is_debit_note': True,
            'internal_type': 'debit_note',
        }</field>
        <field name="search_view_id" ref="account.view_account_invoice_filter"/>
        <field name="help" type="html">
            <p class="o_view_nocontent_smiling_face">
                Create a debit note
            </p>
            <p>
                Note that the easiest way to create a debit note is to do it directly
                from the customer invoice.
            </p>
        </field>
    </record>

    <menuitem action="action_invoice_out_debit_note" id="menu_action_invoice_out_debit_note" parent="account.menu_finance_receivables" sequence="2"/>

    
    <record id="action_vendor_in_debit_note" model="ir.actions.act_window">
        <field name="name">Vendor Debit Notes</field>
        <field name="res_model">account.move</field>
        <field name="view_mode">tree,kanban,form</field>
        <field eval="False" name="view_id"/>
        <field name="domain">[('type','=','in_invoice'), ('is_debit_note', '=', True)]</field>
        <field name="context">{
            'default_type': 'in_invoice',
            'type': 'in_invoice',
            'journal_type': 'purchase',
            'default_is_debit_note': True,
            'internal_type': 'debit_note',
        }</field>
        <field name="search_view_id" ref="account.view_account_invoice_filter"/>
        <field name="help" type="html">
          <p class="o_view_nocontent_smiling_face">
            Record a new vendor debit note
          </p>
        </field>
    </record>

    <menuitem action="action_vendor_in_debit_note" id="menu_action_invoice_in_debit_note" parent="account.menu_finance_payables" groups="l10n_do_debit_note.group_l10n_do_debit_note" sequence="10"/>

</odoo>

1. Instalar el modulo de Nota de Debito de Odoo.

**Configuration information**
Operating System: OdooSH

**Comment by jlopezg** [comment]
Hola @crbll0 

Recién veo este issue.

He intentado reproducirlo pero no lo consigo. Lo que sí veo en el traceback del error es que hace referencia a Odoo Studio.

¿No habrá alguna modificación hecha en Studio que esté provocando el error?

Por favor déjame saber para darle seguimiento a esto.

**Comment by jlopezg** [comment]
Hola @crbll0 

¿Algún update?

**Comment by jlopezg** [comment]
Cerrado por falta de seguimiento.
