### ISSUE TITLE
[BUG][13.0] l10n_do_accounting: No sequence or document number linked to invoice id

### ISSUE THREAD

**Issue by dixgrake** [indexa-git/l10n-dominicana#940]
Type: General

**Describe the bug**
Odoo Version: 13.0

[A clear and concise description of the bug]

When you are logged into the POS with invoiced orders and you create a new product to be able to invoice it, this error occurs.

**Steps to Reproduce**
1. Go to 'App POS'
2. Click on 'New Session '
3. Bill multiple orders, 1 or 2... with the products you have already created before you start.
4. Create a new product, then update the pos and invoice the newly created product.
5. See error

**Expected behavior**
[A clear and concise description of your expectation]

That new products can be invoiced in a pos session already started with invoiced orders.

**Additional context and screenshots**
[Add any other information such as screenshots, videos, messages]

![image](https://user-images.githubusercontent.com/34522768/160056776-ac7112ce-fc71-4cf9-b5cd-eaa3130718f5.png)

(https://pastebin.com/mXwfwFmH)

**Sample Code / Stack Trace**
```
[Traceback (most recent call last):
  File "/opt/odoo/odoo/http.py", line 625, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/http.py", line 311, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/opt/odoo/odoo/http.py", line 670, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/http.py", line 351, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/http.py", line 340, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/http.py", line 916, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/http.py", line 516, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 1342, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/addons/web/controllers/main.py", line 1334, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 386, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 359, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/addons/point_of_sale/models/pos_order.py", line 451, in create_from_ui
    order_ids.append(self._process_order(order, draft, existing_order))
  File "/mnt/extra-addons/l10n-dominicana/l10n_do_pos/models/pos_order.py", line 200, in _process_order
    return super(PosOrder, self)._process_order(order, draft, existing_order)
  File "/opt/odoo/addons/point_of_sale/models/pos_order.py", line 139, in _process_order
    pos_order.action_pos_order_invoice()
  File "/mnt/extra-addons/l10n-dominicana/l10n_do_pos/models/pos_order.py", line 277, in action_pos_order_invoice
    res = super(PosOrder, self).action_pos_order_invoice()
  File "/opt/odoo/addons/point_of_sale/models/pos_order.py", line 409, in action_pos_order_invoice
    new_move.sudo().with_context(force_company=order.company_id.id).post()
  File "/mnt/extra-addons/l10n-dominicana/l10n_do_accounting/models/account_move.py", line 490, in post
    res = super(AccountMove, self).post()
  File "/opt/odoo/addons/sale/models/account_invoice.py", line 75, in post
    res = super(AccountMove, self).post()
  File "/opt/odoo/addons/purchase_stock/models/account_invoice.py", line 168, in post
    return super(AccountMove, self).post()
  File "/opt/odoo/addons/stock_account/models/account_move.py", line 52, in post
    res = super(AccountMove, self).post()
  File "/opt/odoo/addons/l10n_latam_invoice_document/models/account_move.py", line 131, in post
    raise UserError(_('No sequence or document number linked to invoice id %s') % rec.id)
odoo.exceptions.UserError: ('No hay secuencia o número de comprobante vinculado a la factura 7', '')]
```

**Configuration information**
Operating System: Ubuntu 18.04
Python version:

**Comment by andrp92** [comment]
Hello @dixgrake , thanks for submitting this issue. 

We are unable to reproduce this issue. Can you please send us an example of your POS config. This could be relate to the configuration of the sale journal.

**Comment by dixgrake** [comment]
Hi @andrp92, thanks to you.

Explain, 

the error usually does not always occur immediately, if you try to reproduce the steps several times, you will have more possibility that the error comes out.

I have had several cases,

1. with a newly created product, update the pos to load the new product, then the product is invoiced and the error occurs.
2. with the same product, the error has occurred several times with a session initiated.

I hope I have been as clear as possible and that can help you reproduce the error.

share a screenshots of the pos configuration.

pos conf

![image](https://user-images.githubusercontent.com/34522768/164535137-1a75dc45-48ab-4c45-a9e4-a91644f9fa23.png)

fiscal journal

![image](https://user-images.githubusercontent.com/34522768/164535205-ef96e84a-43d0-4394-af88-31651b92ef24.png)


pos journal

![image](https://user-images.githubusercontent.com/34522768/164535280-7134d6c9-a87d-44e1-a2c3-07fa19cad876.png)

**Comment by andrp92** [comment]
Hello @dixgrake, thanks for the detailed information you’ve submitted. 

We will be looking forward to reproducing this issue and notifying you of any findings.

**Comment by akevinieron** [comment]
Why this issue was tagged as l10n_do_accounting being of l10n_do_pos?

Instead of working in this deprecated version, maybe the efforts should be redirected to the new l10n_do_pos v15
