### ISSUE TITLE
Errores al Imprimir NFC Odoo Version 15.0

### ISSUE THREAD

**Issue by mmarmolejos** [indexa-git/l10n-dominicana#993]
![image](https://user-images.githubusercontent.com/87543335/186777001-d54435c0-6dc7-4ec3-8015-0015bfad66c9.png)

Traceback (most recent call last):
  File "C:\Program Files\Odoo Server\server\odoo\addons\base\models\qweb.py", line 219, in render_template
    yield from compiled_fn(self, values, log)
  File "<template_1363>", line 160, in template_1363
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Odoo Server\server\odoo\addons\web\controllers\main.py", line 2021, in report_download
    response = self.report_routes(reportname, docids=docids, converter=converter, context=context)
  File "C:\Program Files\Odoo Server\server\odoo\http.py", line 535, in response_wrap
    response = f(*args, **kw)
  File "C:\Program Files\Odoo Server\server\odoo\addons\web\controllers\main.py", line 1950, in report_routes
    pdf = report.with_context(context)._render_qweb_pdf(docids, data=data)[0]
  File "C:\Program Files\Odoo Server\server\odoo\addons\account\models\ir_actions_report.py", line 49, in _render_qweb_pdf
    return super()._render_qweb_pdf(res_ids=res_ids, data=data)
  File "C:\Program Files\Odoo Server\server\odoo\addons\base\models\ir_actions_report.py", line 896, in _render_qweb_pdf
    html = self_sudo.with_context(context)._render_qweb_html(res_ids, data=data)[0]
  File "C:\Program Files\Odoo Server\server\odoo\addons\base\models\ir_actions_report.py", line 940, in _render_qweb_html
    return self._render_template(self.report_name, data), 'html'
  File "C:\Program Files\Odoo Server\server\odoo\addons\base\models\ir_actions_report.py", line 677, in _render_template
    return view_obj._render_template(template, values).encode()
  File "C:\Program Files\Odoo Server\server\odoo\addons\base\models\ir_ui_view.py", line 1985, in _render_template
    return self.browse(self.get_view_id(template))._render(values, engine)
  File "C:\Program Files\Odoo Server\server\odoo\addons\web_editor\models\ir_ui_view.py", line 29, in _render
    return super(IrUiView, self)._render(values=values, engine=engine, minimal_qcontext=minimal_qcontext)
  File "C:\Program Files\Odoo Server\server\odoo\addons\base\models\ir_ui_view.py", line 1993, in _render
    return self.env[engine]._render(self.id, qcontext)
  File "C:\Program Files\Odoo Server\server\odoo\tools\profiler.py", line 292, in _tracked_method_render
    return method_render(self, template, values, **options)
  File "C:\Program Files\Odoo Server\server\odoo\addons\base\models\ir_qweb.py", line 76, in _render
    result = super()._render(template, values=values, **compile_options)
  File "C:\Program Files\Odoo Server\server\odoo\addons\base\models\qweb.py", line 134, in _render
    result = ''.join(rendering)
  File "C:\Program Files\Odoo Server\server\odoo\addons\base\models\qweb.py", line 221, in render_template
    raise e
  File "C:\Program Files\Odoo Server\server\odoo\addons\base\models\qweb.py", line 219, in render_template
    yield from compiled_fn(self, values, log)
  File "<template_723>", line 73, in template_723
  File "<template_723>", line 69, in t_call_content
  File "C:\Program Files\Odoo Server\server\odoo\addons\base\models\qweb.py", line 221, in render_template
    raise e
  File "C:\Program Files\Odoo Server\server\odoo\addons\base\models\qweb.py", line 219, in render_template
    yield from compiled_fn(self, values, log)
  File "<template_1364>", line 1019, in template_1364
  File "<template_1364>", line 621, in t_call_content
  File "C:\Program Files\Odoo Server\server\odoo\addons\base\models\qweb.py", line 224, in render_template
    error=e, template=template, path=log.get('last_path_node'), code=code)
odoo.addons.base.models.qweb.QWebException: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Program Files\Odoo Server\server\odoo\addons\base\models\qweb.py", line 219, in render_template
    yield from compiled_fn(self, values, log)
  File "<template_1363>", line 160, in template_1363
TypeError: 'NoneType' object is not subscriptable

Error when render the template
TypeError: 'NoneType' object is not subscriptable
Template: l10n_do_accounting.document_tax_totals
Path: /t/t[3]
Node: <t t-set="total_amount_taxed" t-value="l10n_do_amounts['itbis_taxable_amount']"/>

**Comment by mmarmolejos** [comment]
Me olvide comentar que esta error pasa en la versión 15.0,

![image](https://user-images.githubusercontent.com/87543335/186929944-2ac0382a-24bb-4305-a3a3-f074182ffb2e.png)

**Comment by jlopezg** [comment]
Hola @mmarmolejos 

Gracias por reportar el bug.

Ambos errores son el mismo. Estamos trabajándolos.

Por esta via le notificamos cuando quede listo.

**Comment by jlopezg** [comment]
@mmarmolejos corregido.

Por favor actualizar y probar.
